### PR TITLE
Add the `native-tls-vendored` feature to the sdk

### PR DESCRIPTION
**Pull request by labbott**
Needed for reqwest

### CODE REVIEW

**Comment by ahl** [comment]
Why would we put this in the SDK rather than letting consumers of the SDK choose?

**Comment by labbott** [comment]
> Why would we put this in the SDK rather than letting consumers of the SDK choose?

We use `danger_accept_invalid_hostnames` and `danger_accept_invalid_certs` as part of our client_builder in the sdk which are behind this feature (https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs), without this feature the sdk fails to compile when used in the SDK consumer. It seems better to just have the SDK select it.

**Review by ahl — APPROVED** [review]
seems good. we might want to rethink the public interface of the sdk; I think this exposes some of the rough edges between the sdk and cli

**Comment by labbott** [comment]
> seems good. we might want to rethink the public interface of the sdk; I think this exposes some of the rough edges between the sdk and cli

Agreed 100%

**Pull request merged**
