### PR TITLE
Add progress spinner to auth status subcommand

### LINKED ISSUE #567: `oxide auth status` looks like it's hanging when it isn't
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

The help message says `oxide auth status` "verifies and displays information about your authentication state". That could mean (and I think it does mean) that it is actually hitting each configured host to test your creds. I think when I run it, it should print something immediately to say what it's doing. Ideally it would say "Verifying credentials for host abcdef.com..." immediately (maybe even with a spinner to indicate activity!), then print that result as soon as it comes back, and start on the next with a similar message. An less invasive improvement would be to just print _anything_ up front.

### What is the current behaviour and what actions did you take to get there

All I did was run `oxide auth status`.

I have three hosts configured and it sits here for 15 seconds before printing that they're all invalid. I suspect what it's doing is going through the three hosts serially and waiting 5 seconds for each request to time out before it decides they're broken, and then prints all three results at the end.

image

### CLI or SDK version

Oxide CLI 0.2.0, built from commit: 7678a735c68863b4e1b1fbb5506335d9d7dc066e

### Operating system

macOS Sonoma 14.3.1

### PR DESCRIPTION
**Pull request by wfchandler**
When an authenticated Oxide rack is unreachable, e.g. dogfood when the VPN is disabled, `oxide auth status` may take tens of seconds to complete. It is unclear to the user which rack is the source of the delay.

Add a progress spinner that shows the rack currently being checked.

Closes https://github.com/oxidecomputer/oxide.rs/issues/567

### CODE REVIEW

**Comment by wfchandler** [comment]
Video of spinner in action:

https://github.com/user-attachments/assets/ac26b652-c505-4d12-bbfb-452fba8f8cc8

**Review by ahl — COMMENTED** [review]
How does this work with redirected output e.g. oxide auth status >out.txt

**Comment by wfchandler** [comment]
> How does this work with redirected output e.g. oxide auth status >out.txt

`indicatif` [detects non-terminal output targets](https://github.com/console-rs/indicatif/blob/529531726fca07e0a624462838104388e89d029d/src/lib.rs#L74-L76) and hides itself, so if we pipe to a file it won't contain the spinner.

**Review by david-crespo — APPROVED** [review]
This is great, a clear improvement. What do you think about not clearing the "Checking" line when it prints the error? I kind of like keeping the context of what was done. In any case, that's a tiny thing and you can take it or leave it.

Screenshot 2024-07-17 at 12 09 09 PM

Screenshot 2024-07-17 at 12 09 38 PM

**Comment by wfchandler** [comment]
>  What do you think about not clearing the "Checking" line when it prints the error?

I think that looks a bit cleaner, updated.

```sh
$ oxide auth status
  Checking https://oxide.sys.r3.oxide-preview.com...
Profile "oxide" (https://oxide.sys.r3.oxide-preview.com) status: Authenticated
  Checking https://oxide.sys.rack2.eng.oxide.computer...
Profile "oxide2" (https://oxide.sys.rack2.eng.oxide.computer) status: Communication Error: error sending request for url (https://oxide.sys.rack2.eng.oxide.computer/v1/me): operation timed out
```

**Review by ahl — APPROVED** [review]

**Pull request merged**
