### PR TITLE
internet gateway support

### PR DESCRIPTION
**Pull request by rcgoodfellow**
goes along with 

- oxidecomputer/omicron#6475

### CODE REVIEW

**Comment by rcgoodfellow** [comment]
Something odd is going on here. I had to do the following to get the generated code for `internet-gateway ip-pool attach` to work

```diff
diff --git a/cli/src/generated_cli.rs b/cli/src/generated_cli.rs
index 6a37e0f..f2d84e1 100644
--- a/cli/src/generated_cli.rs
+++ b/cli/src/generated_cli.rs
@@ -8788,7 +8788,8 @@ impl<T: CliConfig> Cli<T> {
         }

         if let Some(value) = matches.get_one::<types::NameOrId>("gateway") {
-            request = request.body_map(|body| body.gateway(value.clone()))
+            request = request.body_map(|body| body.gateway(value.clone()));
+            request = request.gateway(value.clone())
         }

         if let Some(value) = matches.get_one::<types::NameOrId>("ip-pool") {
```

Otherwise I get the following

```
$ oxide internet-gateway ip-pool attach  \
  --gateway sv2 \
  --project 'test' \
  --vpc default \
  --ip-pool sv2 \
  --name sv2 \
  --description 'asdf'
error
Invalid Request: gateway was not initialized
```

**Review by ahl — APPROVED** [review]

**Comment by ahl** [comment]
That's a huge problem. I'll investigate async

**Comment by ahl** [comment]
And I'm amazed that CI passed.

**Comment by ahl** [comment]
> Something odd is going on here. I had to do the following to get the generated code for `internet-gateway ip-pool attach` to work

This is a bug in progenitor. In this case we have both a query parameter and a top-level body field named `gateway`. In such a case, I would expect either for generation to fail or to generate a CLI parameter that corresponded to the query parameter with the `--json-body` parameter being mandatory (i.e. because that's the only way to specify that mandatory value).

I think this is **also** reflective of a problem with https://github.com/oxidecomputer/omicron/pull/6475 in that it seems unlikely that we want to specify the target gateway in two places with possibly different values.

**Pull request merged**
